### ISSUE TITLE
Container research is failing

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/serenata-de-amor#347]
```
 ---> Running in 3d8115f3ef00
Downloading datasets (this might take several minutes     depending on your internet connection)
2018-03-22 18:14:41,231 - root - INFO - Could not find config.ini file.
2018-03-22 18:14:41,231 - root - INFO - You need Amazon section in it to interact with S3
2018-03-22 18:14:41,231 - root - INFO - (Check config.ini.example if you need a reference.)
Traceback (most recent call last):
  File "./setup", line 22, in <module>
    fetch_latest_backup(DATA_DIR, force_all=args.all)
  File "/opt/conda/lib/python3.6/site-packages/serenata_toolbox/datasets/__init__.py", line 83, in fetch_latest_backup
    datasets = Datasets(destination_path)
  File "/opt/conda/lib/python3.6/site-packages/serenata_toolbox/datasets/__init__.py", line 59, in __init__
    **self.remote.credentials
TypeError: type object argument after ** must be a mapping, not NoneType
ERROR: Service 'research' failed to build: The command '/bin/sh -c ./setup' returned a non-zero code: 1
```

**Comment by marceloabk** [comment]
I've found this [issue](https://github.com/okfn-brasil/serenata-toolbox/issues/189) in toolbox. Can't be something related?

(I'm trying to start contributing to the sernata de amor. I'll say it again, I hope it's not just a beginner's mistake because of some configuration)
